apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    creationTimestamp: "2022-04-08T21:40:28Z"
    name: pod-reader
    namespace: development
    resourceVersion: "2798"
    uid: 4d7dacee-368e-4a37-8cf0-fbfeb0e2667f
  rules:
  - apiGroups:
    - '*'
    resources:
    - deployments
    - pods
    - pods/log
    - services
    verbs:
    - get
    - list
    - watch
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
